# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - crenovent-backend-container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://crenoventbackendapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d3f77658f46b43799381504d7369bd82 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0bf477d72a584ef5ace287b0e10865ca }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: crenoventbackendapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d3f77658f46b43799381504d7369bd82 }}/crenoback:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'crenovent-backend-container'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f2dcced8012b43179d796807bf47319b }}
        images: 'crenoventbackendapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d3f77658f46b43799381504d7369bd82 }}/crenoback:${{ github.sha }}'